# Generated by Django 5.1.3 on 2024-12-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], max_length=50)),
                ('total_transaksi', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggaran_awal', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_pengeluaran', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youfin_app.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_transaksi', models.CharField(max_length=255)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=50)),
                ('tanggal', models.DateField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youfin_app.kategori')),
            ],
        ),
    ]
