# Generated by Django 5.1.3 on 2024-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfin_app', '0003_category_remove_transaksi_kategori_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], max_length=20),
        ),
    ]
