# Generated by Django 5.1.3 on 2024-12-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youfin_app', '0005_budget_user_category_user_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total_transactions',
        ),
    ]
