# Generated by Django 5.1.3 on 2024-12-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfin_app', '0006_remove_category_total_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_transactions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
