# Generated by Django 5.1.3 on 2024-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youfin_app', '0007_category_total_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
