# Generated by Django 5.1.3 on 2024-12-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youfin_app", "0014_alter_category_category_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("Pemasukan", "Pemasukan"), ("Pengeluaran", "Pengeluaran")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Pemasukan", "Pemasukan"), ("Pengeluaran", "Pengeluaran")],
                max_length=20,
            ),
        ),
    ]
